[metadata]
name = Flask-KVSession-Invenio
version = attr: flask_kvsession.__version__
description = "Transparent server-side session support for flask"
long_description = file: README.rst
license = MIT
author = Marc Brinkmann
author_email = git@marcbrinkmann.de
platforms = any
url = https://github.com/mbr/flask-kvsession
classifiers =
    Development Status :: 5 - Production/Stable

[options]
include_package_data = True
packages = find:
python_requires = >=3.9
zip_safe = False
install_requires =
    flask>=3.0.0
    itsdangerous>=2.0.0
    simplekv>=0.14.0
    werkzeug>=3.1.5

[options.extras_require]
tests =
    docker-services-cli>=0.12.0
    pytest>=6,<9
    redis>=7.0.0
    standard-distutils>=3.11.9
